FROM alpine:3

ADD src/ /opt/epever
#ADD config/ /opt/epever/

# Enable edge repos...
RUN sed -i '/edge/s/^#//' /etc/apk/repositories

RUN apk add --no-cache \
    make \
    g++ \
    gcc \
    php-cli \
    bash \
    composer

WORKDIR /opt/epever

RUN cd /opt/epever && \
    composer install

HEALTHCHECK CMD pgrep php; if [ 0 != $? ]; then exit 1; fi;

CMD ["/bin/bash", "/opt/epever/entrypoint.sh"]
